version: 2.1

orbs:
  node: circleci/node@5
  docker: circleci/docker@1.6.0

executors:
  node-executor:
    docker:
      - image: circleci/node:latest

jobs:
  build-docker:
    docker:
      - image: docker:20.10.7
    working_directory: /home/circleci/project
    environment:
      MONGO_URL: $MONGO_URL
      TOKEN_SECRET: $TOKEN_SECRET
      EDGE_STORE_ACCESS_KEY: $EDGE_STORE_ACCESS_KEY
      EDGE_STORE_SECRET_KEY: $EDGE_STORE_SECRET_KEY
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker Image
          command: |
            docker build \
              --build-arg MONGO_URL=$MONGO_URL \
              --build-arg TOKEN_SECRET=$TOKEN_SECRET \
              --build-arg EDGE_STORE_ACCESS_KEY=$EDGE_STORE_ACCESS_KEY \
              --build-arg EDGE_STORE_SECRET_KEY=$EDGE_STORE_SECRET_KEY \
              -t moviefi-app .
      - run:
          name: Save Docker Image as Tarball
          command: docker save moviefi-app -o moviefi-app.tar
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - moviefi-app.tar

  deploy-docker:
    docker:
      - image: circleci/node:latest
    working_directory: /home/circleci/deploy
    environment:
      MONGO_URL: $MONGO_URL
      TOKEN_SECRET: $TOKEN_SECRET
      EDGE_STORE_ACCESS_KEY: $EDGE_STORE_ACCESS_KEY
      EDGE_STORE_SECRET_KEY: $EDGE_STORE_SECRET_KEY
    steps:
      - attach_workspace:
          at: /home/circleci/deploy
      - add_ssh_keys:
          fingerprints:
            - SHA256:azWrDG0C26Q09r8D01kxy7D78YDQ2k+Nv9bL7S4AGcA
      - run:
          name: Transfer Docker Image to EC2
          command: |
            scp -o StrictHostKeyChecking=no /home/circleci/deploy/moviefi-app.tar ubuntu@ec2-13-50-189-192.eu-north-1.compute.amazonaws.com:/home/ubuntu/moviefi-app.tar
      - run:
          name: Debug Environment Variables in CircleCI
          command: |
            echo $MONGO_URL
            echo "TOKEN_SECRET= TOKEN_SECRET"
            echo "EDGE_STORE_ACCESS_KEY=$EDGE_STORE_ACCESS_KEY"
            echo "EDGE_STORE_SECRET_KEY=$EDGE_STORE_SECRET_KEY"
      - run:
          name: Deploy Docker Image on EC2
          command: |
            ssh -o StrictHostKeyChecking=no -o SendEnv=$MONGO_URL -o SendEnv=$TOKEN_SECRET -o SendEnv=$EDGE_STORE_ACCESS_KEY -o SendEnv=$EDGE_STORE_SECRET_KEY ubuntu@ec2-13-50-189-192.eu-north-1.compute.amazonaws.com \
              echo MONGO_URL=$MONGO_URL && \
              echo TOKEN_SECRET=$TOKEN_SECRET && \
              echo EDGE_STORE_ACCESS_KEY=$EDGE_STORE_ACCESS_KEY && \
              echo EDGE_STORE_SECRET_KEY=$EDGE_STORE_SECRET_KEY && \
              sudo docker load -i /home/ubuntu/moviefi-app.tar && \
              sudo docker stop moviefi-app || true && \
              sudo docker rm moviefi-app || true && \
              sudo docker run -d --name moviefi-app \
                -p 80:3000 \
                -e MONGO_URL=$MONGO_URL \
                -e TOKEN_SECRET=$TOKEN_SECRET \
                -e EDGE_STORE_ACCESS_KEY=$EDGE_STORE_ACCESS_KEY \
                -e EDGE_STORE_SECRET_KEY=$EDGE_STORE_SECRET_KEY \
                moviefi-app && \
              echo 'Deployment complete!'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-docker
      - deploy-docker:
          requires:
            - build-docker
