import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import { EdgeStoreProvider } from "@/lib/edgestore";
import { Toaster } from "react-hot-toast";


// Import Montserrat from Google Fonts
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "600", "700"], // 400 = Regular, 600 = SemiBold, 700 = Bold
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} antialiased bg-background`}>
        <Toaster position="top-center" reverseOrder={false} />
        <div className="justify-center items-center flex">
          <EdgeStoreProvider>{children}</EdgeStoreProvider>
        </div>
        {/* Add fixed positioning for the SVGs */}
        <div className=" w-full ">
          <div className="relative w-full h-[111px] block sm:hidden">
            <Image
              src="/mobildSvg.svg"
              alt="First SVG"
              className="absolute bottom-0 left-0 w-full object-contain"
              layout="intrinsic"
              width={500}
              height={500}
            />
            <Image
              src="/mobildSvg2.svg"
              alt="Second SVG"
              className="absolute bottom-0 left-0 w-full  object-contain"
              layout="intrinsic"
              width={500}
              height={500}
            />
          </div>
          <div className="relative w-full h-[111px] hidden sm:block">
            <Image
              src="/Vector.svg"
              alt="First SVG"
              className="absolute bottom-0 left-0 w-full object-contain"
              layout="intrinsic"
              width={500}
              height={500}
            />
            <Image
              src="/Vector2.svg"
              alt="Second SVG"
              className="absolute bottom-0 left-0 w-full  object-contain"
              layout="intrinsic"
              width={500}
              height={500}
            />
          </div>
        </div>
      </body>
    </html>
  );
}
